name: CBP-NG CI Test

on: [push, pull_request]

jobs:
  test_harcom:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Build test
      shell: bash
      run: ./compile test_harcom
    - name: Run test
      shell: bash
      run: ./test_harcom
  test_cbp_predictors:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        predictor: ["bimodal<>", "bimodalN<>", "tage<>", "gshare<>", "never_taken"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Build predictor
      shell: bash
      run: ./compile cbp -DPREDICTOR="${{ matrix.predictor }}"
    - name: Run predictor
      shell: bash
      run: ./cbp ./gcc_test_trace.gz gcc_test 100 10000
  test_reference_predictor:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Build reference predictor
      shell: bash
      run: g++ -std=c++20 -o reference -O3 reference.cpp -lz
    - name: Run reference predictor
      shell: bash
      run: ./reference ./gcc_test_trace.gz gcc_test 100 10000
